In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("updated_pollution_dataset.csv")

In [4]:
df1=df.drop('Air Quality', axis=1)

In [5]:
df1

,Temperature,Humidity,PM2.5,PM10,NO2,SO2,CO,Proximity_to_Industrial_Areas,Population_Density
0,29.8,59.1,5.2,17.9,18.9,9.2,1.72,6.3,319
1,28.3,75.6,2.3,12.2,30.8,9.7,1.64,6.0,611
2,23.1,74.7,26.7,33.8,24.4,12.6,1.63,5.2,619
3,27.1,39.1,6.1,6.3,13.5,5.3,1.15,11.1,551
4,26.5,70.7,6.9,16.0,21.9,5.6,1.01,12.7,303
...,...,...,...,...,...,...,...,...,...
4995,40.6,74.1,116.0,126.7,45.5,25.7,2.11,2.8,765
4996,28.1,96.9,6.9,25.0,25.3,10.8,1.54,5.7,709
4997,25.9,78.2,14.2,22.1,34.8,7.8,1.63,9.6,379
4998,25.3,44.4,21.4,29.0,23.7,5.7,0.89,11.6,241
4999,24.1,77.9,81.7,94.3,23.2,10.5,1.38,8.3,461

In [8]:
def series_periodos(inicio, periodos, freq): 
    serie = pd.date_range(start=inicio, periods=periodos, freq=freq)
    return serie

In [11]:
indice=series_periodos('1/1/2010',df1.shape[0],'D')

In [12]:
df1.index=indice

In [13]:
df1.to_csv("Preprocesado.csv",index_label="indice")